version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Analytics.API/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-api
    ports:
      - "${API_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Redis__Host=redis
      # --- CORREÇÃO APLICADA AQUI ---
      # A variável agora é RabbitMQ__HostName para corresponder à propriedade na classe C#.
      - RabbitMQ__HostName=${RABBITMQ_HOST} 
      - RabbitMQ__UserName=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASS}
      - RabbitMQ__Port=${RABBITMQ_NODE_PORT}
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:16
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    ports:
      - "${REDIS_PORT}:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
    ports:
      - "${RABBITMQ_NODE_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

volumes:
  pgdata:
