# | Etapa                | O que faz                                                |
# | -------------------- | -------------------------------------------------------- |
# | `FROM sdk`           | Usa a imagem do SDK para compilar a aplicação            |
# | `COPY *.sln`         | Copia o arquivo da solução e `.csproj` de cada projeto   |
# | `RUN dotnet restore` | Restaura os pacotes NuGet                                |
# | `RUN dotnet publish` | Compila a aplicação e gera os arquivos de build          |
# | `FROM aspnet`        | Usa a imagem mais leve de runtime para rodar a aplicação |
# | `COPY --from=build`  | Copia os arquivos compilados                             |
# | `ENTRYPOINT`         | Inicia a aplicação                                       |


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln ./
COPY Analytics.API/*.csproj ./Analytics.API/
COPY Analytics.Application/*.csproj ./Analytics.Application/
COPY Analytics.Domain/*.csproj ./Analytics.Domain/
COPY Analytics.Infrastructure/*.csproj ./Analytics.Infrastructure/

RUN dotnet restore

COPY . .

WORKDIR /src/Analytics.API
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 80

ENTRYPOINT ["dotnet", "Analytics.API.dll"]
